version: "3.8"
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - api
    volumes:
      - ./middleware:/var/lib/https-portal
    restart: always
    environment:
      DOMAINS: 'co-friend-dev.sci-co.co.jp -> http://api:8080'
      STAGE: 'production'
  api:
    container_name: "api"
    volumes:
      - ./backend/api:/api
      - ./backend/models:/models
      - ./backend/abi:/abi
      - ./backend/prompts:/prompts
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    env_file:
      - .env