version: "3.0"

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - api
    restart: always
    environment:
      DOMAINS: 'co-friend-dev.sci-co.co.jp -> http://api:8080'
      STAGE: 'production'
      PROXY_CONNECT_TIMEOUT: 300
      PROXY_SEND_TIMEOUT: 300
      PROXY_READ_TIMEOUT: 300

  api:
    container_name: "api"
    volumes:
      - ./api:/api
      - ./models:/models
    build: .
    ports:
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    env_file:
      - .env

  